### ISSUE TITLE
Custom element doesn't exist: webrtc-camera

### ISSUE THREAD

**Issue by Dim3333** [AlexxIT/WebRTC#260]
Hello,

Home Assistant 2022.2.6
Same issue that anothers posts : _Custom element doesn't exist: webrtc-camera_ but I don't find the solution.

The integration seems to be well installed.

Could you help me ?

Thanks

**Comment by Botond24** [comment]
You need to also add the `WebRTC` integration to home-assistant via the Integrations page.

**Comment by Dim3333** [comment]
Already done. Port min/max ?
![image](https://user-images.githubusercontent.com/43283756/153960163-8ca10290-9bf8-475e-852a-c6304c70b14c.png)

**Comment by Dim3333** [comment]
I changed the rtsp port to 254 and it's works.

**Comment by alexvenom** [comment]
I'm running into this same problem: "Custom element doesn't exist: webrtc-camera".
- WebRTC installed correctly via HACS
- WebRTC Camera installed via Configuration -> Integrations

Any thoughts?

**Comment by slash133** [comment]
I have the same problem since my update on homeassistant, my integration is not loaded and i don t understant for why
![webrtc1](https://user-images.githubusercontent.com/13819132/154834195-8bc4f9c3-e2d0-42a5-9e93-e7e31e646717.png)
![webrtc2](https://user-images.githubusercontent.com/13819132/154834226-587f797e-8ca6-409d-81d4-83e4893a7959.png)
any ideas?
if you have ideas ? 
thks

**Comment by fedemartino** [comment]
same problem on version: 2022.3.0
![image](https://user-images.githubusercontent.com/13227691/157152500-3591f5eb-202a-4871-bbed-bd9527368c3d.png)

any ideas?

**Comment by lolfonfire** [comment]
I've been using this integration for some weeks now.
Setup was easy but it's not stable. I'm not sure if this is due Home Assistant updates or the integration itself.
Yesterday I've updated Home Assistant to core-2022.3.3. After the Home Assistant update none of my camera were visible in Lovelace. Error: Custom element doesn't exist: webrtc-camera

As shown in the following screenshot the integration is added/loaded. Sometimes when I press F5 the "webrtc-camera" integration is loaded and the error is gone => Camera visible.
Last week I had a similar issue in the HA Companion app on Android. I needed to sign-out the HA app and sign-in again. Then the "Custom element doesn't exist: webrtc-camera" error was gone.
![image](https://user-images.githubusercontent.com/50797554/157916403-c8cedb00-a3e5-4737-a02d-50ccb73efb7d.png)

**Comment by BabaBoch1** [comment]
> I've been using this integration for some weeks now. Setup was easy but it's not stable. I'm not sure if this is due to Home Assistant updates or the integration itself. Yesterday I've updated Home Assistant to core-2022.3.3. After the Home Assistant update none of my cameras were visible in Lovelace. Error: Custom element doesn't exist: webrtc-camera
> 
> As shown in the following screenshot the integration is added/loaded. Sometimes when I press F5 the error is gone and cameras are visible. Last week I had a similar issue in the HA Companion app on Android. I needed to sign-out the HA app and sign-in again. Then the "Custom element doesn't exist: webrtc-camera" error was gone. This was before the update to core-2022.3.3. ![image](https://user-images.githubusercontent.com/50797554/157916403-c8cedb00-a3e5-4737-a02d-50ccb73efb7d.png)
> 
> After pressing F5 a few more times it sometimes shows this: ![image](https://user-images.githubusercontent.com/50797554/157918288-36cb4ed7-0ad5-49c5-a83e-5a862ccfcf3f.png)

Same problem here.  I gave up on this and deleted it all today.

**Comment by Dim3333** [comment]
Hi,

None issues from my side with the last version of HA.

**Comment by wowgamr** [comment]
Same error for me after update to 2022.3.3.

**Comment by MagellanOo** [comment]
Same issue for me after update to 2022.3.4

**Comment by wowgamr** [comment]
In my case the problem resolved itself. Camera is working again.

**Comment by jaegerschnitzel** [comment]
I ca

> I've been using this integration for some weeks now. Setup was easy but it's not stable. I'm not sure if this is due to Home Assistant updates or the integration itself. Yesterday I've updated Home Assistant to core-2022.3.3. After the Home Assistant update none of my cameras were visible in Lovelace. Error: Custom element doesn't exist: webrtc-camera
> 
> As shown in the following screenshot the integration is added/loaded. Sometimes when I press F5 the error is gone and cameras are visible. Last week I had a similar issue in the HA Companion app on Android. I needed to sign-out the HA app and sign-in again. Then the "Custom element doesn't exist: webrtc-camera" error was gone. This was before the update to core-2022.3.3. ![image](https://user-images.githubusercontent.com/50797554/157916403-c8cedb00-a3e5-4737-a02d-50ccb73efb7d.png)
> 
> After pressing F5 a few more times it sometimes shows this: ![image](https://user-images.githubusercontent.com/50797554/157918288-36cb4ed7-0ad5-49c5-a83e-5a862ccfcf3f.png)

Same for me.

**Comment by Mark612** [comment]
Using 'master', with the latest home assistant, sometimes it works. Sometimes it does not. Refresh and restarting sometimes helps.

**Comment by lolfonfire** [comment]
Yeah if i hit F5 like 5-6 times then suddenly it works. Then I close the webinterface/app when I open it again it's broken again.
Again hitting F5 and it works ...

**Comment by fgonza2** [comment]
same issue here.   In my Raspi based HA container doesnt work, on my NUC based HA container it works.   2022.3.4 version on both

WebRT Camera  "Not Loaded"  on the integrations page

**Comment by mortenmoulder** [comment]
Chipping in to say I've got the same issue.

**Comment by mishoboss** [comment]
Same issue here. It's a strange one, because it seems to be random - sometimes it loads the card, sometimes it can't. More often it can't.

**Comment by MercerK** [comment]
Hi folks.

It looks like Home Assistant and GitHub are pointing to 2.1.0, instead of the latest version 2.2.0. This could be due to the way the author managed the release for the very last one (as it doesn't even show up in the releases list). If you have 2.1.0, you may be encountering this issue. I would recommend uninstalling that version and manually installing version 2.2.0 available here (https://github.com/AlexxIT/WebRTC/releases/tag/v2.2.0).

Once I did this, it started to work.

**Comment by fgonza2** [comment]
> Hi folks.
> 
> It looks like Home Assistant and GitHub are pointing to 2.1.0, instead of the latest version 2.2.0. This could be due to the way the author managed the release for the very last one (as it doesn't even show up in the releases list). If you have 2.1.0, you may be encountering this issue. I would recommend uninstalling that version and manually installing version 2.2.0 available here (https://github.com/AlexxIT/WebRTC/releases/tag/v2.2.0).
> 
> Once I did this, it started to work.

I can confirm that this FIXES the issue.    Had to do manual install to 2.20 and it works!    so the bug is on HACS installation

**Comment by fedemartino** [comment]
> > Hi folks.
> > It looks like Home Assistant and GitHub are pointing to 2.1.0, instead of the latest version 2.2.0. This could be due to the way the author managed the release for the very last one (as it doesn't even show up in the releases list). If you have 2.1.0, you may be encountering this issue. I would recommend uninstalling that version and manually installing version 2.2.0 available here (https://github.com/AlexxIT/WebRTC/releases/tag/v2.2.0).
> > Once I did this, it started to work.
> 
> I can confirm that this FIXES the issue. Had to do manual install to 2.20 and it works! so the bug is on HACS installation

This solved it! thanks!

**Comment by Mark612** [comment]
> 
> Once I did this, it started to work.

Yes, this helps for web browsers. However, is it working for your mobile companion application? It is still problematic for me.

**Comment by georaspi** [comment]
> > Once I did this, it started to work.
> 
> Yes, this helps for web browsers. However, is it working for your mobile companion application? It is still problematic for me.

Same issue here. Browser working ok, not on Android up though... A bit disappointed.

**Comment by maximatchev** [comment]
> > > Once I did this, it started to work.
> > 
> > 
> > Yes, this helps for web browsers. However, is it working for your mobile companion application? It is still problematic for me.
> 
> Same issue here. Browser working ok, not on Android up though... A bit disappointed.

Same for me

**Comment by AlexxIT** [comment]
GitHub recently had a bug. That's where the latest release got lost ([2.2.0](https://github.com/AlexxIT/WebRTC/releases/tag/v2.2.0)).

You need:
- install it manually or
- install latest master version via HACS or
- wait next release

**Comment by wowgamr** [comment]
Lovelace card still broken on v2.3.0

**Comment by AlexxIT** [comment]
@wowgamr what mobile OS do you use? What lovelace mode do you use?

**Comment by wowgamr** [comment]
Android 10 (MIUI 12). Home Assistant mobile app v2022.3.0-full
```
lovelace:
  mode: yaml
```
Card:
```
  - type: 'custom:webrtc-camera'
	url: 'rtsp://login:password@192.168.1.171:554/stream1'
	ui: true
	ptz:
	  service: tapo_control.ptz
	  data_left:
		entity_id: camera.tapo_c200_hd
		pan: LEFT
	  data_right:
		entity_id: camera.tapo_c200_hd
		pan: RIGHT
	  data_up:
		entity_id: camera.tapo_c200_hd
		tilt: UP
	  data_down:
		entity_id: camera.tapo_c200_hd
		tilt: DOWN
```

![image](https://user-images.githubusercontent.com/4518407/162788427-6867606f-a85d-49d3-a713-402ea4695d9f.png)

**Comment by AlexxIT** [comment]
Oh. Lovelace mode yaml always have some problems

**Comment by wowgamr** [comment]
It worked fine for the few months, and broke after update to 2022.3. I think the problem is in HA.

**Comment by homeoneautomacao** [comment]
I did extensive testing on a newer version of HA and concluded that the "custom element doesn't exist:webrtc-camera" problem occurs when:
1) lovelace: yaml activated
2) only on HA version 2022.3.1 or higher (2022.2.9 with webrtc 2.2.0 works fine)
3) only on android or iphone app (Browser from PC works normal)
Now I really don't know if the problem is in HA or Webrtc, but as all other integrations work normally, my first suspicion is, something has changed in HA in version 2022.3.1 that AlexxIT may need to make some modification on the webrtc side .

PS: I tested on 3 different servers, on all of them just disable lovelace:yaml and it works again.

**Comment by McDAlexander** [comment]
Hi All. I ran into this problem and didn't have any luck manually copying over WebRTC into the custom-components folder. I also tried to copy the webrtc-camera.js into the root webrtc folder within custom-components.  

What I did to solve my problem was look in HA Configurations -> Dashboards -> Resources and verified if the webrtc-camera.js resource was loaded. Turns out it was added and at the end of the resource there was "?v2.2.0" appended onto the end. I removed the ?v2.2.0 and the resource started working properly.

**Comment by bigsem89** [comment]
i have same issue webrtc v.2.3.0, HA 2022.4.1

**Comment by uncle-wong** [comment]
> 

Same for me  WebRTC Camera "Not Loaded" on the integrations page v23.0

**Comment by vks007** [comment]
> Hi All. I ran into this problem and didn't have any luck manually copying over WebRTC into the custom-components folder. I also tried to copy the webrtc-camera.js into the root webrtc folder within custom-components.
> 
> What I did to solve my problem was look in HA Configurations -> Dashboards -> Resources and verified if the webrtc-camera.js resource was loaded. Turns out it was added and at the end of the resource there was "?v2.2.0" appended onto the end. I removed the ?v2.2.0 and the resource started working properly.

Thanks this worked for me too with v2.3.0 , I also removed the version from the end of the resource and it works - on browser , iOS app and Android app.
Changed -> /webrtc/webrtc-camera.js?v2.3.0
To /webrtc/webrtc-camera.js

**Comment by SvenBre** [comment]
Is it perhaps possible that this problem has to do with the way AlexxIT is packaging the module? I noticed that the file webrtc-camera.js is in a subfolder of the integration folder, i.e. not where other community frontend modules are placing their js-files. As a user of Lovelace's yaml mode, I was pointing to that file from my configuration.yaml:

`- url: /hacsfiles/webrtc/www/webrtc-camera.js`
`  type: module`

It was working but I have seen the phenomenon discussed here: Several times a day, especially after restarting HA, the card got lost with "custom element doesn't exist". None of the solutions suggested here had worked or were what I wanted (switch to storage mode).

What I did yesterday is copying the files under "/custom_components/webrtc/www/" into a newly created folder "/www/community/webrtc/" (a softlink may also have worked and would be preferable) and pointed to that path in configuration.yaml:

`- url: /hacsfiles/webrtc/webrtc-camera.js`
`    type: module`

I don't know whether that makes any sense, but I haven't seen the phenomenon ever since. The card seems to be stable now. Is that working for other users too?

**Comment by AlexxIT** [comment]
Because this is not frontend integration. This is custom component.

**Comment by SvenBre** [comment]
Sure. But obviously something is causing trouble for yaml-mode users. I can meanwhile confirm my workaround. The problem hasn't occurred again in 4 days. Thanks, AlexxIT, for a wonderful integration!

**Comment by AlexxIT** [comment]
The right link to script is
https://github.com/AlexxIT/WebRTC/blob/3e1099d65cf66ac7b7e1bcc787722f48f25c6bea/custom_components/webrtc/__init__.py#L74

No one should move this file to www folder or use /local link or use /hacsfiles link.

I think yaml users are just make problem for themselves with using yaml mode... Because default UI mode support configure UI via YAML and also handle links to external resources properly.

**Comment by Smokeayelot** [comment]
How do I remove this action off my device ?

**Comment by Smokeayelot** [comment]
How to remove this off my phone Simone put this and several
More on my phone to spy and send them weird stuff how to remove this
!?!?!!!

**Comment by bigsem89** [comment]
> The right link to script is
> 
> https://github.com/AlexxIT/WebRTC/blob/3e1099d65cf66ac7b7e1bcc787722f48f25c6bea/custom_components/webrtc/__init__.py#L74
> 
> No one should move this file to `www` folder or use `/local` link or use `/hacsfiles` link. It just work from its place with this link.
> 
> I think yaml users are just make problem for themselves with using yaml mode... Because default UI mode support configure UI via YAML and also handle links to external resources properly.

I'm using UI mode. The same issue. I've tried delete all file and reinstall integration. Nothing helps.

**Comment by AlexxIT** [comment]
@bigsem89 you need to have latest integration version (2.3). It should be installed and configured without any errors in Hass log

**Comment by bigsem89** [comment]
> @bigsem89 you need to have latest integration version (2.3). It should be installed and configured without any errors in Hass log

It 2.3... no errors in log

**Comment by urielz** [comment]
> Is it perhaps possible that this problem has to do with the way AlexxIT is packaging the module? I noticed that the file webrtc-camera.js is in a subfolder of the integration folder, i.e. not where other community frontend modules are placing their js-files. As a user of Lovelace's yaml mode, I was pointing to that file from my configuration.yaml:
> 
> `- url: /hacsfiles/webrtc/www/webrtc-camera.js` ` type: module`
> 
> It was working but I have seen the phenomenon discussed here: Several times a day, especially after restarting HA, the card got lost with "custom element doesn't exist". None of the solutions suggested here had worked or were what I wanted (switch to storage mode).
> 
> What I did yesterday is copying the files under "/custom_components/webrtc/www/" into a newly created folder "/www/community/webrtc/" (a softlink may also have worked and would be preferable) and pointed to that path in configuration.yaml:
> 
> `- url: /hacsfiles/webrtc/webrtc-camera.js` ` type: module`
> 
> I don't know whether that makes any sense, but I haven't seen the phenomenon ever since. The card seems to be stable now. Is that working for other users too?

I can confirm that this solved the issue for me as well. Something is clearly broken. This fix, albeit temporary, works well.

**Comment by webphantom115** [comment]
If I use HACS installation, I always get “Custom element doesn’t exist” error and no errors in log. Doesn’t matter what version, 2.3, 2.2, master etc
If I use manual installation I see “Restart connection” for my camera and for Bunny stream. The error is “Error opening stream (ERRORTYPE_110, Operation timed out)”. 
In VLC both streams work fine

Unfortunately, have to uninstall (

**Comment by SoulEater45** [comment]
Currently running version `2.3.1` and it was working for a short time and then I started getting the error. Using a few hints here, I tried to make a link using:
```bash
mkdir -p /config/www/community/webrtc-my
ln -s /config/custom_components/webrtc/www/webrtc-camera.js /config/www/community/webrtc-my/webrtc-camera.js
```
Then I added the following to my resources.yaml:
```yaml
- url: /local/community/webrtc-my/webrtc-camera.js
  type: module
```

For now it works as it should! Hope this helps someone.

**Comment by ceolsine** [comment]
I blame HA. When I was finally able to get HAC to add the integration, it appears in HACs but there is no folder or js file in the /community. I added the folder and the js file then had to manually add the resource in HA and finally the card appeared as an option. I'm fighting connectivity issues, but the card at least appears.
Think I'm just going to skip the direct camera feed and add camera views from Blue Iris.

**Comment by clangren** [comment]
Posting in late on this one, but the solution for me was to add this to configuration.yaml:

> lovelace:
>   mode: yaml
>   resources:
>     - url: /custom_components/webrtc/www/webrtc-camera.js
>       type: module

To confirm it loaded: Go to Settings, Dashboards, click the three dots in the upper right, Resources. You should have a new JavaScript Module for /custom_components/webrtc/www/webrtc-camera.js.

Then everything worked: WebRTC Camera v2.3.1 and Home Assistant 2022.9.5.

**Comment by Smokeayelot** [comment]
Hey how do u turn / cancel all the builds with my gmail account someone
hacked my gmail and yea yea so I’m trying to get this off my phone and etc

**Comment by grantjus** [comment]
This is still an issue in v2.3.1 and HA 2022.10.5 installed via HACS 1.28.3.

The resource file is missing from the list of registered resources under Settings > Dashboards > ... > Resources.

I've turned on info logging for HACS, and nothing looks particularly interesting to me.  

`
2022-10-24 01:11:42.591 DEBUG (MainThread) [custom_components.hacs] <Integration AlexxIT/WebRTC> Getting repository information
2022-10-24 01:11:43.123 DEBUG (MainThread) [custom_components.hacs] <Integration AlexxIT/WebRTC> Running checks against v2.3.1
2022-10-24 01:11:43.973 DEBUG (MainThread) [custom_components.hacs] <HacsData async_write> Saving data
2022-10-24 01:11:43.974 DEBUG (MainThread) [custom_components.hacs] <HACSStore async_save_to_store> Did not store data for 'hacs.hacs'. Content did not change
2022-10-24 01:11:46.982 DEBUG (MainThread) [custom_components.hacs] <Integration AlexxIT/WebRTC> Getting repository information
2022-10-24 01:11:47.470 DEBUG (MainThread) [custom_components.hacs] <Integration AlexxIT/WebRTC> Running checks against v2.3.1
2022-10-24 01:11:48.350 INFO (MainThread) [custom_components.hacs] <Integration AlexxIT/WebRTC> Running pre installation steps
2022-10-24 01:11:48.351 INFO (MainThread) [custom_components.hacs] <Integration AlexxIT/WebRTC> Pre installation steps completed
2022-10-24 01:11:48.351 INFO (MainThread) [custom_components.hacs] <Integration AlexxIT/WebRTC> Running installation steps
2022-10-24 01:11:48.351 DEBUG (MainThread) [custom_components.hacs] <Integration AlexxIT/WebRTC> Getting repository information
2022-10-24 01:11:48.809 DEBUG (MainThread) [custom_components.hacs] <Integration AlexxIT/WebRTC> Running checks against v2.3.1
2022-10-24 01:11:49.727 DEBUG (MainThread) [custom_components.hacs] <Integration AlexxIT/WebRTC> Local path is set to /config/custom_components/webrtc
2022-10-24 01:11:49.727 DEBUG (MainThread) [custom_components.hacs] <Integration AlexxIT/WebRTC> Remote path is set to custom_components/webrtc
2022-10-24 01:11:49.728 DEBUG (MainThread) [custom_components.hacs] <QueueManager> Checking out tasks to execute
2022-10-24 01:11:49.728 DEBUG (MainThread) [custom_components.hacs] <QueueManager> Starting queue execution for 13 tasks
2022-10-24 01:11:49.728 DEBUG (MainThread) [custom_components.hacs] <Integration AlexxIT/WebRTC> Downloading __init__.py
2022-10-24 01:11:49.728 DEBUG (MainThread) [custom_components.hacs] Downloading https://raw.githubusercontent.com/AlexxIT/WebRTC/v2.3.1/custom_components/webrtc/__init__.py
2022-10-24 01:11:49.729 DEBUG (MainThread) [custom_components.hacs] <Integration AlexxIT/WebRTC> Downloading config_flow.py
2022-10-24 01:11:49.729 DEBUG (MainThread) [custom_components.hacs] Downloading https://raw.githubusercontent.com/AlexxIT/WebRTC/v2.3.1/custom_components/webrtc/config_flow.py
2022-10-24 01:11:49.730 DEBUG (MainThread) [custom_components.hacs] <Integration AlexxIT/WebRTC> Downloading manifest.json
2022-10-24 01:11:49.730 DEBUG (MainThread) [custom_components.hacs] Downloading https://raw.githubusercontent.com/AlexxIT/WebRTC/v2.3.1/custom_components/webrtc/manifest.json
2022-10-24 01:11:49.730 DEBUG (MainThread) [custom_components.hacs] <Integration AlexxIT/WebRTC> Downloading services.yaml
2022-10-24 01:11:49.730 DEBUG (MainThread) [custom_components.hacs] Downloading https://raw.githubusercontent.com/AlexxIT/WebRTC/v2.3.1/custom_components/webrtc/services.yaml
2022-10-24 01:11:49.731 DEBUG (MainThread) [custom_components.hacs] <Integration AlexxIT/WebRTC> Downloading ca.json
2022-10-24 01:11:49.731 DEBUG (MainThread) [custom_components.hacs] Downloading https://raw.githubusercontent.com/AlexxIT/WebRTC/v2.3.1/custom_components/webrtc/translations/ca.json
2022-10-24 01:11:49.732 DEBUG (MainThread) [custom_components.hacs] <Integration AlexxIT/WebRTC> Downloading en.json
2022-10-24 01:11:49.732 DEBUG (MainThread) [custom_components.hacs] Downloading https://raw.githubusercontent.com/AlexxIT/WebRTC/v2.3.1/custom_components/webrtc/translations/en.json
2022-10-24 01:11:49.733 DEBUG (MainThread) [custom_components.hacs] <Integration AlexxIT/WebRTC> Downloading it.json
2022-10-24 01:11:49.733 DEBUG (MainThread) [custom_components.hacs] Downloading https://raw.githubusercontent.com/AlexxIT/WebRTC/v2.3.1/custom_components/webrtc/translations/it.json
2022-10-24 01:11:49.733 DEBUG (MainThread) [custom_components.hacs] <Integration AlexxIT/WebRTC> Downloading pl.json
2022-10-24 01:11:49.733 DEBUG (MainThread) [custom_components.hacs] Downloading https://raw.githubusercontent.com/AlexxIT/WebRTC/v2.3.1/custom_components/webrtc/translations/pl.json
2022-10-24 01:11:49.734 DEBUG (MainThread) [custom_components.hacs] <Integration AlexxIT/WebRTC> Downloading pt_br.json
2022-10-24 01:11:49.734 DEBUG (MainThread) [custom_components.hacs] Downloading https://raw.githubusercontent.com/AlexxIT/WebRTC/v2.3.1/custom_components/webrtc/translations/pt_br.json
2022-10-24 01:11:49.735 DEBUG (MainThread) [custom_components.hacs] <Integration AlexxIT/WebRTC> Downloading zh-Hant.json
2022-10-24 01:11:49.735 DEBUG (MainThread) [custom_components.hacs] Downloading https://raw.githubusercontent.com/AlexxIT/WebRTC/v2.3.1/custom_components/webrtc/translations/zh-Hant.json
2022-10-24 01:11:49.912 INFO (MainThread) [custom_components.hacs] <Integration AlexxIT/WebRTC> Download of config_flow.py completed
2022-10-24 01:11:49.922 INFO (MainThread) [custom_components.hacs] <Integration AlexxIT/WebRTC> Download of en.json completed
2022-10-24 01:11:49.933 INFO (MainThread) [custom_components.hacs] <Integration AlexxIT/WebRTC> Download of it.json completed
2022-10-24 01:11:49.944 INFO (MainThread) [custom_components.hacs] <Integration AlexxIT/WebRTC> Download of zh-Hant.json completed
2022-10-24 01:11:49.953 INFO (MainThread) [custom_components.hacs] <Integration AlexxIT/WebRTC> Download of services.yaml completed
2022-10-24 01:11:49.971 INFO (MainThread) [custom_components.hacs] <Integration AlexxIT/WebRTC> Download of __init__.py completed
2022-10-24 01:11:49.976 INFO (MainThread) [custom_components.hacs] <Integration AlexxIT/WebRTC> Download of pt_br.json completed
2022-10-24 01:11:49.977 INFO (MainThread) [custom_components.hacs] <Integration AlexxIT/WebRTC> Download of ca.json completed
2022-10-24 01:11:49.996 INFO (MainThread) [custom_components.hacs] <Integration AlexxIT/WebRTC> Download of manifest.json completed
2022-10-24 01:11:50.016 INFO (MainThread) [custom_components.hacs] <Integration AlexxIT/WebRTC> Download of pl.json completed
2022-10-24 01:11:50.913 DEBUG (MainThread) [custom_components.hacs] <Integration AlexxIT/WebRTC> Downloading utils.py
2022-10-24 01:11:50.913 DEBUG (MainThread) [custom_components.hacs] Downloading https://raw.githubusercontent.com/AlexxIT/WebRTC/v2.3.1/custom_components/webrtc/utils.py
2022-10-24 01:11:50.922 DEBUG (MainThread) [custom_components.hacs] <Integration AlexxIT/WebRTC> Downloading index.html
2022-10-24 01:11:50.922 DEBUG (MainThread) [custom_components.hacs] Downloading https://raw.githubusercontent.com/AlexxIT/WebRTC/v2.3.1/custom_components/webrtc/www/index.html
2022-10-24 01:11:50.934 DEBUG (MainThread) [custom_components.hacs] <Integration AlexxIT/WebRTC> Downloading webrtc-camera.js
2022-10-24 01:11:50.934 DEBUG (MainThread) [custom_components.hacs] Downloading https://raw.githubusercontent.com/AlexxIT/WebRTC/v2.3.1/custom_components/webrtc/www/webrtc-camera.js
2022-10-24 01:11:51.071 INFO (MainThread) [custom_components.hacs] <Integration AlexxIT/WebRTC> Download of index.html completed
2022-10-24 01:11:51.143 INFO (MainThread) [custom_components.hacs] <Integration AlexxIT/WebRTC> Download of webrtc-camera.js completed
2022-10-24 01:11:51.144 INFO (MainThread) [custom_components.hacs] <Integration AlexxIT/WebRTC> Download of utils.py completed
2022-10-24 01:11:52.146 DEBUG (MainThread) [custom_components.hacs] <QueueManager> Queue execution finished for 13 tasks finished in 2.42 seconds
2022-10-24 01:11:52.146 INFO (MainThread) [custom_components.hacs] <Integration AlexxIT/WebRTC> Installation steps completed
2022-10-24 01:11:52.146 INFO (MainThread) [custom_components.hacs] <Integration AlexxIT/WebRTC> Running post installation steps
2022-10-24 01:11:52.146 INFO (MainThread) [custom_components.hacs] Reloading custom_component cache
2022-10-24 01:11:52.149 INFO (SyncWorker_0) [homeassistant.loader] Loaded hacs from custom_components.hacs
2022-10-24 01:11:52.149 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-10-24 01:11:52.150 INFO (SyncWorker_0) [homeassistant.loader] Loaded webrtc from custom_components.webrtc
2022-10-24 01:11:52.150 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration webrtc which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-10-24 01:11:52.151 INFO (MainThread) [custom_components.hacs] Custom_component cache reloaded
2022-10-24 01:11:52.153 INFO (MainThread) [custom_components.hacs] <Integration AlexxIT/WebRTC> Post installation steps completed
2022-10-24 01:11:52.153 DEBUG (MainThread) [custom_components.hacs] <HacsData async_write> Saving data`

**Comment by AlexxIT** [comment]
This is **Integration** (custom_component). Not **Frontend** custom card.
It will not appear in the folder `/config/www/community`. And should never have appeared there.
JS file is in the component folder. And publicly available through the link `/webrtc/webrtc-camera.js`.
Not `/local/...`. Not `/hacsfiles/...`. Not `/custom_components/...`. But `/webrtc/webrtc-camera.js`.

**Comment by grantjus** [comment]
Well, this is embarrassing.

Turns out I still needed to install the integration in HA after HACS was done installing it.  This issue is fixed from my side.

**Comment by renslinden** [comment]
> This is **Integration** (custom_component). Not **Frontend** custom card.
> It will not appear in the folder `/config/www/community`. And should never have appeared there.
> JS file is in the component folder. And publicly available through the link `/webrtc/webrtc-camera.js`.
> Not `/local/...`. Not `/hacsfiles/...`. Not `/custom_components/...`. But `/webrtc/webrtc-camera.js`.

I read the entire thread but still not clear to me what the actual solution is for Android devices. Chrome on Android works fine but the HA app on Android doesn't...

```
Custom element doesn't exist: webrtc-camera.

type: custom:webrtc-camera
entity: camera.my_camera
```

**Comment by pergolafabio** [comment]
anyone got it running on HA Android companion app? i cant get the card loaded, clearing cache on Companion app jus doesnt work...

Chrome browsers are working fine with 3.0.0 update...
Tried with or without adding below in resources, just doesnt help

```
  - url: /hacsfiles/webrtc/webrtc-camera.js?v3.0.0
    type: js 
```

**Comment by djooberlee** [comment]
> anyone got it running on HA Android companion app? i cant get the card loaded, clearing cache on Companion app jus doesnt work...
> 
> Chrome browsers are working fine with 3.0.0 update... Tried with or without adding below in resources, just doesnt help
> 
> ```
>   - url: /hacsfiles/webrtc/webrtc-camera.js?v3.0.0
>     type: js 
> ```

Looks like I have the same problem.
Because it works everywhere except for the Android application.
```
Custom elemet doesn't exist: webrtc-camera
```

**Comment by pergolafabio** [comment]
i had the same, i forgot the "="

it needs to be like:
```

  - url: /hacsfiles/webrtc/webrtc-camera.js?v=3.0.0
    type: js 
```

**Comment by djooberlee** [comment]
> I've been using this integration for some weeks now. Setup was easy but it's not stable. I'm not sure if this is due to Home Assistant updates or the integration itself. Yesterday I've updated Home Assistant to core-2022.3.3. After the Home Assistant update none of my cameras were visible in Lovelace. Error: Custom element doesn't exist: webrtc-camera
> 
> As shown in the following screenshot the integration is added/loaded. Sometimes when I press F5 the error is gone and cameras are visible. Last week I had a similar issue in the HA Companion app on Android. I needed to sign-out the HA app and sign-in again. Then the "Custom element doesn't exist: webrtc-camera" error was gone. This was before the update to core-2022.3.3. ![image](https://user-images.githubusercontent.com/50797554/157916403-c8cedb00-a3e5-4737-a02d-50ccb73efb7d.png)
> 
> After pressing F5 a few more times it sometimes shows this: ![image](https://user-images.githubusercontent.com/50797554/157918288-36cb4ed7-0ad5-49c5-a83e-5a862ccfcf3f.png)

Thanks, logout then login really works for me

**Comment by rfenouil** [comment]
Hi, running into the same issue.
Card for my Reolink doorbell shows ok in regular browser but not in app companion.

Version 3.1.0, added from UI.
Home Assistant 2023.4.5 - Frontend 20230411.1 - latest

**Comment by TomKranenburg** [comment]
Just an update, I solved this issue by going to edit mode in the dashboard at the top right:

![Mc2vOshJqN](https://user-images.githubusercontent.com/10760232/236614075-3082d0da-a226-4a03-8c38-5dc410531610.png)

The the top right again select "Manage Resources":

![icWp0rbpkg](https://user-images.githubusercontent.com/10760232/236614113-f05940c1-469d-4ca0-9202-65f8ef81bf81.png)

You should see the WebRTC script being loaded here:

![iGKD4c1g3w](https://user-images.githubusercontent.com/10760232/236614147-2b8ff99f-e539-4a13-a131-648621c9d256.png)

Just add a "=" symbol between the v and the version number like so:

![Z8tO91EGh0](https://user-images.githubusercontent.com/10760232/236614197-a7578660-6d09-45d7-b610-ca460817a769.png)

Then restart. This fixed it for me. Somewhere there will be a component throwing a fit over the URL parameter not being perfect probably. It might even be browser dependant.

**Comment by kvikindi** [comment]
You lovely human bean! This absolutely fixed it for me! Cheers.

**Comment by ams3401** [comment]
Going through the same problem on Android phone only. All internet browsers work fine and no issue on iPhone App.
Adding the resource stated above in configuration.yaml didn't resolve the issue.

**Comment by AlexxIT** [comment]
Once again. Check if link works for you `http://hassip:8123/webrtc/webrtc-camera.js`

The component automatically configures resources when setting up the integration. If you don't use "lovelace mode yaml" and older browsers - you shouldn't have a problem.

Possible problems:

- you haven't setup integration
- you using "lovelace mode yaml" and haven't setup resources (do not use this mode if you do not know how to use it)
- you copy `webrtc-camera.js` to `www`/`hacsfiles`/`community ` and broke something (this was a bad idea)
- you using mobile app and have problems with cache
- you using an old browser, which is causing JavaScript errors for this component

**Comment by bigsem89** [comment]
> 

Non of this related to me.

**Comment by fgonza2** [comment]
this should be your #1 issue.  I updated to 3.2.1 still custom element doesn't exist.   Nto sure what else to do, even manually installing 3.2.1 doesn't work anymore

**Comment by bigsem89** [comment]
the same.

**Comment by fikander** [comment]
Perhaps this should be obvious, but after couple hours of debugging I realised, that *integrations don't get set up unless there's configuration entry using them*.
For me, webrtc wasn't setup up (no services, no custom card), until I added artificial entry using `platform: webrtc` in `configuration.yaml` and restarted HA:

```
media_player:
  - platform: webrtc
    name: Dummy camera
    stream: some_stream
    audio: pcmu/48000
```
What helped with debugging was turning logging on to observe what integrations are being set up with 

```
logger:
  default: info
  logs:
    custom_components: debug
```

Hope that helps!

**Comment by AlexxIT** [comment]
Integration don't get setup if you not setup it...

https://github.com/AlexxIT/WebRTC#configuration

**Comment by fikander** [comment]
Lol. Thanks @AlexxIT. I missed that step indeed!
Just starting with the system and tried to find out in the HA core how integrations get set up. They need some configuration, and I missed the fact, that installing it via HACS doesn't actually create one.

**Comment by AlexxIT** [comment]
Yes. HACS just download integration source code. Hass won't use this new code if you not ask it.

**Comment by Ayuus** [comment]
Just installed, and found incorrect url at "manage resoursources"

`/webrtc/webrtc-camera.js?v=v3.3.0`

should be

`/webrtc/webrtc-camera.js?v=3.3.0`

(note the v before the 3)

**Comment by Ayuus** [comment]
Both changes were necessary to make it work for me...

**Comment by Ayuus** [comment]
Tried again, now original setup works. Note that second rtsp in 'rtsp://rtsp:12345678@192.168.1.123:554/av_stream/ch0'` is username.

**Comment by AdrianGarside** [comment]
For those confused why adding it by HACS, restarting HA, then adding it as an integration still gave this error. Ctrl-Shift-F5 to force a refresh of the browser was necessary for me to fix it. I'd added a card manually and pasted the content in because it wasn't showing as an available custom card. At which point I got the error. And after fixing the error the ctrl-shift-F5 it also then showed as an available custom card.

**Comment by tclemos** [comment]
> * you haven't setup integration

that's it! 🎉

**Comment by jturn08** [comment]
I'm missing the webrtc camera lovelace card in the default dashboard (I'm not using a custom dashboard). Any tips on how to troubleshoot?

In Home Assistant logs, I see error message "Setup failed for 'type': Integration not found." after updating HomeAssistant configuration.yaml to add type: 'custom:webrtc-camera'.

- WebRTC installed correctly via HACS
- WebRTC Camera installed via Configuration -> Integrations
- Successfully configured go2rtc.yaml and go2rtc web page and cameras are viewable at http://homeassistant.local:1984/

**Comment by AlexxIT** [comment]
If `/webrtc/webrtc-camera.js` working for you - you probably using lovelace mode yaml without manual including this link to resources.

**Comment by jturn08** [comment]
> If `/webrtc/webrtc-camera.js` working for you - you probably using lovelace mode yaml without manual including this link to resources.

Thanks for trying to help, but it doesn't seem like I am not using lovelace mode yaml (my `configuration.yaml` doesn't have `lovelace: mode: yaml`). 

Under Settings -> Dashboards, I see "Overview" dashboard. If I select Overview dashboard, I see "The default dashboard, Overview, cannot be edited from the UI. You can hide it by setting another dashboard as default."

Under Settings -> Dashboards, after I click the three dots menu (top-right) and select Resources, I see an entry for a JavaScript modeul with URL = "/webrtc/webrtc-camera.js?v=v3.5.1"

On the Overview dashboard, after I click the three dots menu (top-right) and select "Edit dashboard", and then  after I click the three dots menu (top-right) and select "Raw configuration editor", I see the following

```
strategy:
  type: original-states
  areas:
    hidden:
      - bedroom_2
    order:
      - bedroom
      - bedroom_3
```

If WebRTC isn't displayed on the default "Overview" dashboard by default without editing dashboard configuration, that's fine. I can create a custom dashboard. But I was expecting WebRTC cameras to be automatically displayed on the default "Overview" dashboard.

**Comment by zeddski** [comment]
> Just an update, I solved this issue by going to edit mode in the dashboard at the top right:
> 
> ![Mc2vOshJqN](https://user-images.githubusercontent.com/10760232/236614075-3082d0da-a226-4a03-8c38-5dc410531610.png)
> 
> The the top right again select "Manage Resources":
> 
> ![icWp0rbpkg](https://user-images.githubusercontent.com/10760232/236614113-f05940c1-469d-4ca0-9202-65f8ef81bf81.png)
> 
> You should see the WebRTC script being loaded here:
> 
> ![iGKD4c1g3w](https://user-images.githubusercontent.com/10760232/236614147-2b8ff99f-e539-4a13-a131-648621c9d256.png)
> 
> Just add a "=" symbol between the v and the version number like so:
> 
> ![Z8tO91EGh0](https://user-images.githubusercontent.com/10760232/236614197-a7578660-6d09-45d7-b610-ca460817a769.png)
> 
> Then restart. This fixed it for me. Somewhere there will be a component throwing a fit over the URL parameter not being perfect probably. It might even be browser dependant.

Mine was slightly different, but your answer did give me a clue:
![image](https://github.com/AlexxIT/WebRTC/assets/5345629/12d9d695-64dc-4e11-b004-349be47d4dfd)
This was my URL. Removed the second "v", with this result:
![image](https://github.com/AlexxIT/WebRTC/assets/5345629/e7ed2119-ec5c-4004-bfec-515f630a1d30)
And now I have a working card. Now, to configure the camera's....

**Comment by Jurrjuna** [comment]
> > Just an update, I solved this issue by going to edit mode in the dashboard at the top right:
> > ![Mc2vOshJqN](https://user-images.githubusercontent.com/10760232/236614075-3082d0da-a226-4a03-8c38-5dc410531610.png)
> > The the top right again select "Manage Resources":
> > ![icWp0rbpkg](https://user-images.githubusercontent.com/10760232/236614113-f05940c1-469d-4ca0-9202-65f8ef81bf81.png)
> > You should see the WebRTC script being loaded here:
> > ![iGKD4c1g3w](https://user-images.githubusercontent.com/10760232/236614147-2b8ff99f-e539-4a13-a131-648621c9d256.png)
> > Just add a "=" symbol between the v and the version number like so:
> > ![Z8tO91EGh0](https://user-images.githubusercontent.com/10760232/236614197-a7578660-6d09-45d7-b610-ca460817a769.png)
> > Then restart. This fixed it for me. Somewhere there will be a component throwing a fit over the URL parameter not being perfect probably. It might even be browser dependant.
> 
> Mine was slightly different, but your answer did give me a clue: ![image](https://private-user-images.githubusercontent.com/5345629/319925200-12d9d695-64dc-4e11-b004-349be47d4dfd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzODQ2NDcsIm5iZiI6MTcxMjM4NDM0NywicGF0aCI6Ii81MzQ1NjI5LzMxOTkyNTIwMC0xMmQ5ZDY5NS02NGRjLTRlMTEtYjAwNC0zNDliZTQ3ZDRkZmQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDZUMDYxOTA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjZjYjZjYTY3OWI2NmI3MTQ3OWM1ODE2ZDRhN2UzZDJkNmU3NmY0ZWRkMTVmZGMxMTVlODE5ZTNhNzZiNmRkZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Xb-eeKql7DEDljJy1nt28vdL6bjYPNJmPW7DMd_y6YU) This was my URL. Removed the second "v", with this result: ![image](https://private-user-images.githubusercontent.com/5345629/319925354-e7ed2119-ec5c-4004-bfec-515f630a1d30.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzODQ2NDcsIm5iZiI6MTcxMjM4NDM0NywicGF0aCI6Ii81MzQ1NjI5LzMxOTkyNTM1NC1lN2VkMjExOS1lYzVjLTQwMDQtYmZlYy01MTVmNjMwYTFkMzAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDZUMDYxOTA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTgyOWE0ZGVmYjkzNjNjMjA1ZDNlMTAwMGE1YmU1ODY3YTQ4NzczNjg0MmMyNzFlM2VhYzMzMjUzMzhmYjFlZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.j2yaHvACOPCDB1CiloSWAR7pkH0kOnC6gnN_4tZ-pZw) And now I have a working card. Now, to configure the camera's....

It didn't solve my issue when casting to chromecast. I noticed /webrtc/webrtc-camera.js?v=3.5.1 changed back to /webrtc/webrtc-camera.js?v=v3.5.1 after restart HA.  Am I doing something wrong or is it stored somewhere else?

**Comment by mrreview** [comment]
> > Just an update, I solved this issue by going to edit mode in the dashboard at the top right:
> > ![Mc2vOshJqN](https://user-images.githubusercontent.com/10760232/236614075-3082d0da-a226-4a03-8c38-5dc410531610.png)
> > The the top right again select "Manage Resources":
> > ![icWp0rbpkg](https://user-images.githubusercontent.com/10760232/236614113-f05940c1-469d-4ca0-9202-65f8ef81bf81.png)
> > You should see the WebRTC script being loaded here:
> > ![iGKD4c1g3w](https://user-images.githubusercontent.com/10760232/236614147-2b8ff99f-e539-4a13-a131-648621c9d256.png)
> > Just add a "=" symbol between the v and the version number like so:
> > ![Z8tO91EGh0](https://user-images.githubusercontent.com/10760232/236614197-a7578660-6d09-45d7-b610-ca460817a769.png)
> > Then restart. This fixed it for me. Somewhere there will be a component throwing a fit over the URL parameter not being perfect probably. It might even be browser dependant.
> 
> Mine was slightly different, but your answer did give me a clue: ![image](https://private-user-images.githubusercontent.com/5345629/319925200-12d9d695-64dc-4e11-b004-349be47d4dfd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA5NTcyNjEsIm5iZiI6MTcyMDk1Njk2MSwicGF0aCI6Ii81MzQ1NjI5LzMxOTkyNTIwMC0xMmQ5ZDY5NS02NGRjLTRlMTEtYjAwNC0zNDliZTQ3ZDRkZmQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTRUMTEzNjAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzJlNmNhYTFmYjBmYzBhYzRmY2RiZjhmYTA3NDBlM2Q0MDQxNTZlM2JlYjU1ODIxYjI2NzYyODYwOWY0ZDA0OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.mlF2f-VH3trlH9PTpX_MCesTvMGI3naD6IyZIsD2CIs) This was my URL. Removed the second "v", with this result: ![image](https://private-user-images.githubusercontent.com/5345629/319925354-e7ed2119-ec5c-4004-bfec-515f630a1d30.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA5NTcyNjEsIm5iZiI6MTcyMDk1Njk2MSwicGF0aCI6Ii81MzQ1NjI5LzMxOTkyNTM1NC1lN2VkMjExOS1lYzVjLTQwMDQtYmZlYy01MTVmNjMwYTFkMzAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTRUMTEzNjAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Yjg2MGE3YjYzZGVhMDkzZmIwMmVjYjY2ZTJhM2VhZDljNzYxNDY3MGIzMWU3OTRjNDc5ZmQ0MzIwYjY4YmMxZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.dYLheWb1Ka7zusjsFgriJIiSoRkxpbma3rVWmts5ztA) And now I have a working card. Now, to configure the camera's....

That did the trick. Thank you.

**Comment by ENWOD** [comment]
I am experiencing this same issue with a Home Assistant Container, Go2RTC running in a docker and Web2RTC installed.

I can view a video stream using a customer Web2RTC card but when I try to cast a dashboard with a panel layout. I get this error on my Google Nest display.

Any ideas - I've tried the "v=" removal of the resource mentioned above but no luck and nothing showing in the logs.

**Comment by ChayoteJarocho** [comment]
The `/webrtc/webrtc-camera.js` method worked for me. I was seeing this problem in my laptop's web browser.

But before removing/adding the js resource, I first made sure that I could access that javascript file directly by going to http://homeassistant.local:8123/webrtc/webrtc-camera.js (or whatever your url is). If the file loads, then the next step is to add the version to see if it loads. I appended `?v=3.6.0` (that's the version of the integration that's installed in my HA at the moment) and I could confirm it loaded correctly.

Lastly, I added the resource to the dashboard per the instructions above. But the important part here is to REFRESH the webpage after doing that, because the javascript file does not get loaded automatically after you add the resouce, meaning that if you go back to the dashboard to try to add a `custom:webrtc-camera` card again, you will keep seeing the same failure!

I'm surprised Home Assistant does not reload the page automatically for me after adding the javascript resource. Considering HA suggested me to refresh the page after I _deleted_ a resource, I don't see why not suggest the same when adding it. Oh well.

I _think_ I saw some comments above suggesting to reload/restart HA after updating the javascript resource, but that won't work if you keep the browser page open without refreshing it: the js resource won't get loaded!

Anyway, after refreshing, you can add the `custom:webrtc-camera` card to your dashboard. The error should go away, and you'll be able to see the camera preview.

**Comment by AlexxIT** [comment]
`webrtc-camera.js` is a static file. Any query parameters (e.g. `?v=3.6.0`) have no effect on static files at all.
The only thing they affect is requesting the file bypassing the cache. The value of this parameter is completely unimportant.
It could be anything. For example `/webrtc/webrtc-camera.js?i_hate_element_not_exist_error=1`.

**Comment by kanagawawave** [comment]
If you have trouble finding the "Manage resources" button, enable the Advanced Mode:
https://developers.home-assistant.io/docs/frontend/custom-ui/registering-resources/

**Comment by david-forster10** [comment]
I've started setting up my integration today after installing via HACs. When enabling debugging on the module, I'm finding this error in the logs:

```
2025-01-05 23:18:40.055 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to open with args ('/config/go2rtc.yaml', 'w') inside the event loop by custom integration 'webrtc' at custom_components/webrtc/config_flow.py, line 90: with open(path, "w") as f: (offender: /config/custom_components/webrtc/config_flow.py, line 90: with open(path, "w") as f:), please create a bug report at https://github.com/AlexxIT/WebRTC/issues
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#open
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 227, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 213, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 154, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 707, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 678, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 2033, in _run_once
    handle._run()
  File "/usr/local/lib/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_protocol.py", line 559, in start
    task = asyncio.Task(coro, loop=loop, eager_start=True)
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_protocol.py", line 480, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_app.py", line 569, in _handle
    return await handler(request)
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 83, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 86, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
    response = await handler(request)
  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
    result = await handler(request, **request.match_info)
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 81, in with_admin
    return await func(self, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 222, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 74, in wrapper
    return await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 122, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 341, in async_configure
    result = await self._async_configure(flow_id, user_input)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 388, in _async_configure
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 491, in _async_handle_step
    result: _FlowResultT = await getattr(flow, method)(user_input)
  File "/config/custom_components/webrtc/config_flow.py", line 90, in async_step_config
    with open(path, "w") as f:
```

Rebooting my HA instance has then enabled the custom-card without having to include anything in the configuration.yaml.

**Comment by Gangoke** [comment]
Mine was a browser cache issue. In chrominum based browsers, F12 to open devtools, then click and hold the refresh button(the normal browser refresh button) It'll give you more options, click "Empty cache and hard reload"

**Comment by aam1972** [comment]
> Mine was a browser cache issue. In chrominum based browsers, F12 to open devtools, then click and hold the refresh button(the normal browser refresh button) It'll give you more options, click "Empty cache and hard reload"

worked for me, thanks!

**Comment by khmyznikov** [comment]
@bLd75 thanks for fix, got exactly the same problem.
CC @AlexxIT
