### ISSUE TITLE
Background mobile data usage with Home Assistant App + possible Chrome tab

### ISSUE THREAD

**Issue by reflexsa** [AlexxIT/WebRTC#274]
Hi all,

I seem to be having an issue with background data usage when using the WebRTC cards on my dashboards. It looks like the app drains most of my mobile data, but a chrome tab with HA open may also be doing something similar.
I have since switched back to the picture card and those issues have gone away.
I see there was a similar issue [https://github.com/AlexxIT/WebRTC/issues/62](url) that was closed, but this was more related to battery drain.

Any advice would be appreciated.

**Comment by AlexxIT** [comment]
This problem should be fixed. But more testing may be needed

**Comment by Beylie** [comment]
I have had the same issue for the last 2 months, poof! mobile data gone! Happy to help out with testing if you tell me how.

**Comment by leadingbump** [comment]
This is still an issue for me as well. Chrome and the companion app on android.

**Comment by AlexxIT** [comment]
Check latest beta https://github.com/AlexxIT/WebRTC/releases/tag/v3.0-beta.1

**Comment by jcgoette** [comment]
Qualitatively, beta is a big improvement in battery, data, and Lovelace load times. 👍🏻

**Comment by AlexxIT** [comment]
Should be fixed in v3

**Comment by reflexsa** [comment]
Awesome thank you! Haven't had a chance to test it yet but hopefully will in the next week or two
