### ISSUE TITLE
Lovelace 'Uncaught Error'

### ISSUE THREAD

**Issue by Gferretta** [AlexxIT/WebRTC#30]
Hi Alex
I Uninstalled everything, both in **HACS** and in **Configuration -> Integrations.**
Clear the cache.
Restart my HA
Install WebRTC only in **HACS** and the error was does NOT appear in log.
When I install the integration in **Configuration -> Integrations**., without even putting the card in with video, only with a refresh of screen, _**the error already appears in Lovelace**_.

I leave you a video that may help you to determine what is happening to me.
https://photos.app.goo.gl/kQdqTa5eWLkgkFw66

Regards

PS Sorry for posting into Sonoff and not the WebRTC repository.

![115821167-a87d9d00-a3d8-11eb-9521-8bfdf8b91736](https://user-images.githubusercontent.com/65413059/115891214-35057b00-a42c-11eb-8b40-1f746c804d6d.jpg)

**Comment by Michsior14** [comment]
Looks like I have similar issue. In the browser console I can see this:

`Uncaught DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "webrtc-camera" has already been used with this registry
    at http://<ha-adress>:8123/webrtc/webrtc-camera.js:355:16`

**Comment by AlexxIT** [comment]
Fixed in v1.4.0

**Comment by majkers** [comment]
Still getting this in android when trying to access via nabu casa:

`https://XXXXX.ui.nabu.casa/lovelace/default_view:0:0 Uncaught
https://XXXX.ui.nabu.casa/lovelace/11:0:0 Uncaught`

**Comment by AlexxIT** [comment]
Browser cache...

**Comment by majkers** [comment]
I do not know how to clean andred companion cache so I removed its data and stilll no fix. I used android chrome's private window so not to use browser cache and same result

**Comment by AlexxIT** [comment]
@majkers may be you have added JS card to resources manually?

**Comment by majkers** [comment]
@AlexxIT no I used HASC and updating your great addon via it. I experience this stuff and not playing video only on my android phone when using mobile 3G/LTE connection and connection to mu HA instance via nabu casa. When I connect the same phone to my wi-fi so without nabu cassa as proxy everything is working just fine using the same app and very same chrome browser. BUT. When connecting to my HA via nabu casa on PC from chrome is is also working fine. So to sum up. Only android connection via nabu casa is not working for me :(

**Comment by AlexxIT** [comment]
PC + NabuCasa + 3G/LTE = works?
Android + NabuCasa + 3G/LTE = doesn't?

**Comment by majkers** [comment]
I'd rather say:
PC/Android + Local/Wi-fi = works
PC + NabuCasa = works
Android + NabuCasa =doesn't work
