### ISSUE TITLE
Version 3

### ISSUE THREAD

**Issue by AlexxIT** [AlexxIT/WebRTC#368]
- [x] Update custom card for support go2rtc streamer
- [x] Check built-in go2rtc application
- [x] Check go2rtc stream names
- [x] Check entity camera url
- [x] Check Home Assistant Cast
- [x] Check DashCast
- [x] Check public link
- [x] Check go2rtc add-on
- [x] Check Frigate 12 add-on
- [x] Update readme
- [x] Fix fullscreen in Safari
- [x] Example snapshot to Telegram

**Comment by serlinGi** [comment]
hi, 
I updated to the beta version via HACS on my HA.OS; unfortunately the display of my cameras in the card doesn't start (stuck on "loading1"). 
I cleared the cache; 
I checked that the go2rtc system is working properly: I can view the stream pointing directly to the IP of my HA on port 1984 both in h264 and h265 without problems or slowdowns (it's very good). Am I missing some step or have I misunderstood something?

P.S.  I did the installation and tests by remotely connecting with my mobile phone; 
I tried both with public FQDN and direct VPN to my LAN

**Comment by vampywiz17** [comment]
I tried it. It working well, with h264. With h265, it working about 3-4 sec (hurray!) but after it infinitely loading. (i tried with Windows 10, latest Chrome browser)

**Comment by sunnysingh-84** [comment]
Having issues since upgrading too, I'm pulling some Tapo C200 streams from Synology Surveillance Station (proxy) and getting the following error:

ERROR: NotSupportedError: Failed to execute 'addSourceBuffer' on 'MediaSource': The type provided (video/mp4;codecs="undefined" ) is unsupported.

**Comment by fuatakgun** [comment]
+1 (ERROR: NotSupportedError: Failed to execute 'addSourceBuffer' on 'MediaSource': The type provided ('video/mp4; codecs="undefined"') is unsupported.)

**Comment by doudz** [comment]
got the same
![image](https://user-images.githubusercontent.com/1262548/210268807-323a8761-b7c8-4a54-a8e2-92a6e875ce33.png)

**Comment by AlexxIT** [comment]
@doudz Version 3 no longer displays the icon on the top right. You do not run version 3

**Comment by doudz** [comment]
it's strange ...
using http://[address]:1984/ dashboard, it works

**Comment by AlexxIT** [comment]
I don't know about `video/mp4;codecs="undefined"` problem. Try beta.2, maybe it will fix something.
`loading1` also strange error. This means that the HA did not respond to the very first request for a connection link.

All users should make sure that they are not using the old card because of browser cache. Mobile applications can be especially problematic.

**Comment by doudz** [comment]
I was using beta-1, it works with beta-2 !

**Comment by doudz** [comment]
there's a browser cache problem too ;-)

**Comment by vampywiz17** [comment]
> I tried it. It working well, with h264. With h265, it working about 3-4 sec (hurray!) but after it infinitely loading. (i tried with Windows 10, latest Chrome browser)

I updated it to Beta 2 but not help. Now i try it with Edge but same problem. It seems after 4 sec, it start buffering, but nothing happen (only the center cam is h265):

![image](https://user-images.githubusercontent.com/14281430/210271892-ec5a8560-48ed-4525-93bc-8875cb221448.png)

**Comment by rudizl** [comment]
Still 'loading1' after beta 2.

**Comment by vampywiz17** [comment]
@AlexxIT 

it possible to  help you:

![image](https://user-images.githubusercontent.com/14281430/210272766-88d1b4ad-b2f1-468c-b4df-f5efc0b08f82.png)

**Comment by rudizl** [comment]
And the errors from my installation:
`Logger: homeassistant.components.stream.stream.camera.kidsroom_cam
Source: components/stream/__init__.py:434
Integration: Stream (documentation, issues)
First occurred: 21:40:41 (1 occurrences)
Last logged: 21:40:41

Error from stream worker: Error opening stream (ERRORTYPE_111, Connection refused) rtsp://****:****@192.168.8.61:554/av_stream/ch0`
`Logger: frontend.js.latest.202212131
Source: components/system_log/__init__.py:256
First occurred: 21:40:42 (2 occurrences)
Last logged: 21:40:44

http://192.168.8.103:8123/webrtc/webrtc-camera.js?v3.0.0-beta.2:78:19 Uncaught TypeError: Cannot read properties of undefined (reading 'callWS')`

**Comment by Zelete** [comment]
> Still 'loading1' after beta 2.

Do you use the vertical stack card by any chance? If I individually add 3 WebRTC cams to a test page they all load fine here for some reason.

I have the following errors in my logs:

```
http://192.168.21.3:8123/webrtc/webrtc-camera.js?v3.0.0-beta.2:78:19 Uncaught TypeError: Cannot read properties of undefined (reading 'callWS')
http://192.168.21.3:8123/webrtc/video-rtc.js:391:27 Uncaught NotSupportedError: Failed to execute 'addSourceBuffer' on 'MediaSource': The type provided ('video/mp4; codecs="avc1."') is unsupported.
http://192.168.21.3:8123/webrtc/video-rtc.js:315:22 Uncaught TypeError: this.ondata is not a function
http://192.168.21.3:8123/webrtc/video-rtc.js:402:31 Uncaught InvalidStateError: Failed to read the 'buffered' property from 'SourceBuffer': This SourceBuffer has been removed from the parent media source.
http://192.168.21.3:8123/webrtc/video-rtc.js:509:31 Uncaught TypeError: Cannot read properties of null (reading 'connectionState')
```

**Comment by mrthosi** [comment]
Hi,

Home Assistant's Picture Elements Card with webrtc components is scrambled. (3.0 b2; it worked with 2.x) 

With disabled cameras (**all elements are showed at their right places**; red placeholders show camera streams' locations):
![image](https://user-images.githubusercontent.com/55213305/210274901-cb048ca7-5361-4564-9e6f-8aa2fc35dd15.png)
With enabled cameras (**camera streams are at wrong places, other elements are also broken**): 
![image](https://user-images.githubusercontent.com/55213305/210275508-fe495773-5f72-4086-aa2f-acbe7c64e8c0.png)

Style used: (one of them)
        style:
          top: 70%
          left: 88%
          width: 25%
Left and width seems to be ok, top is changed since 2.x.

Regardless of this, streams are ok for me (HIKVISON cameras, H264).
Standalone webrtc card is OK.

**Comment by rudizl** [comment]
> > Still 'loading1' after beta 2.
> 
> Do you use the vertical stack card by any chance? If I individually add 3 WebRTC cams to a test page they all load fine here for some reason.
> 
> I have the following errors in my logs:
> 
> ```
> http://192.168.21.3:8123/webrtc/webrtc-camera.js?v3.0.0-beta.2:78:19 Uncaught TypeError: Cannot read properties of undefined (reading 'callWS')
> http://192.168.21.3:8123/webrtc/video-rtc.js:391:27 Uncaught NotSupportedError: Failed to execute 'addSourceBuffer' on 'MediaSource': The type provided ('video/mp4; codecs="avc1."') is unsupported.
> http://192.168.21.3:8123/webrtc/video-rtc.js:315:22 Uncaught TypeError: this.ondata is not a function
> http://192.168.21.3:8123/webrtc/video-rtc.js:402:31 Uncaught InvalidStateError: Failed to read the 'buffered' property from 'SourceBuffer': This SourceBuffer has been removed from the parent media source.
> http://192.168.21.3:8123/webrtc/video-rtc.js:509:31 Uncaught TypeError: Cannot read properties of null (reading 'connectionState')
> ```

Yes, vertical and horizontal stack. Tomorrow will try with separate card.

**Comment by iceatcs** [comment]
Yeah I can confirm if WebRTC card inside vertical/horizontal (maybe also Grid) will get stuck loading1.

**Comment by sunnysingh-84** [comment]
> > Having issues since upgrading too, I'm pulling some Tapo C200 streams from Synology Surveillance Station (proxy) and getting the following error:
> > ERROR: NotSupportedError: Failed to execute 'addSourceBuffer' on 'MediaSource': The type provided (video/mp4;codecs="undefined" ) is unsupported.
> 
> I should add that this error message is displayed when using custom:webrtc-camera card.

FIXED - I found that I had an old entry in my dashboards resources therefore I removed '/local/webrtc-camera.js'  😄

**Comment by sunnysingh-84** [comment]
> @doudz Version 3 no longer displays the icon on the top right. You do not run version 3

Thanks for sharing this, it lead to me to discover that I had two entries in my dashboards resource file (one for the old '/local/webrtc-camera.js' and another for the new plugin '/webrtc/webrtc-camera.js?v3.0.0-beta.2' ). Once removing the old entry the streaming is now working again!

**Comment by Flyer11111** [comment]
removed old entries as above cameras worked once went back to page nothing restarted HA . could see cams once went back to page again no streams Full restore back to old version everything working again.

**Comment by AlexxIT** [comment]
@vampywiz17 Are you using the latest version of go2rtc? I can't repeat the error on my H265 camera. I have fixed something similar before.

**Comment by Flyer11111** [comment]
v3.0-beta.2/1 ?  I've just had a look  i did it a few hours ago has their been an update in the last few hours ?

**Comment by AlexxIT** [comment]
[x] `video/mp4;codecs="undefined"` - problem because old card in browser cache (you shouldn't have icon in top right corner)
[x] `loading1` and `callWS` - problem because card inside Stack card, fixed in `beta.3`
[x] card inside Picture Elements Card, fixed in `beta.3`
[ ] H265 problem, can't reproduce on my camera, not fixed

**Comment by rudizl** [comment]
Strange, but after updating to beta 3 I still receive this error:
```
Logger: frontend.js.latest.202212131
Source: components/system_log/__init__.py:256
First occurred: 09:35:43 (3 occurrences)
Last logged: 09:36:04

https://......ui.nabu.casa/webrtc/webrtc-camera.js?v3.0.0-beta.2:78:19 Uncaught TypeError: Cannot read properties of undefined (reading 'callWS')
```
As you can see, there is still `webrtc-camera.js?v3.0.0-beta.2:78:19`

**Comment by Flyer11111** [comment]
some streams would not load after a few ctrl-f5's .it would stop displaying any rolled back to old , using beta.3 

android app no streams , msc   on the streams that loaded ,old version  rtc how do i change that ? some audio 

type: custom:webrtc-camera
url: rtsp://admin:XXXXXXXXX@192.168.X.XXX:554/h264Preview_01_sub

reolink cameras


thanks

**Comment by vampywiz17** [comment]
> @vampywiz17 Are you using the latest version of go2rtc? I can't repeat the error on my H265 camera. I have fixed something similar before.

Ahh found the problem.

I use hikvison cams with h265+ coding. if i disable the "+" feature, it working well.

What do you think, it possible to do this with "+" feature?

**Comment by AlexxIT** [comment]
@vampywiz17 I don't know what is "+" feature. Maybe something proprietary from hikvison. They may use an encoding standard not very suitable for live streaming to the browser.

@Flyer11111 I can't understand what you're writing. Your translator is probably very bad.

**Comment by vampywiz17** [comment]
> @vampywiz17 I don't know what is "+" feature. Maybe something proprietary from hikvison. They may use an encoding standard not very suitable for live streaming to the browser.

https://www.hikvision.com/en/core-technologies/storage-and-bandwidth/h-265-plus/

What's H.265+?

An intelligent algorithm self-developed by Hikvision that can greatly decrease the bitrate of video based on a standard H.265 codec. Hikvision's H.265+ is such an optimized video encoding technology based on the standard H.265/ High efficiency Video Coding (HEVC) format. 

 

With H.265+, video quality nearly matches that of H.265/HEVC but reduces the transmission bandwidth and storage capacity required, due to three key technologies — prediction encoding, noise suppression, and flexible bitrate control.

 

It demonstrates incredible improvements in bandwidth reduction, data storage efficiency, and video content analyses.

**Comment by mikedrawback** [comment]
I'm on beta-3. Restarted and cleared browser cache. Still getting the 'loading' error. Mine says 'loading2' on my HA dashboard. I took it out of a grid card and confirmed the resources on my dashboard are updated. still having the same issue.

If I try to view the stream from http://[address]:1984 it says 'loading' and this is what I see in the console:

```
video-rtc.js:391 Uncaught DOMException: Failed to execute 'addSourceBuffer' on 'MediaSource': The type provided ('video/mp4; codecs="avc1.276400,mp4a.40.2"') is unsupported.
    at onmessage.mse (http://XX.XX.XX.XX:1984/video-rtc.js:391:27)
    at WebSocket.<anonymous> (http://XX.XX.XX.XX:1984/video-rtc.js:312:41)
onmessage.mse @ video-rtc.js:391
(anonymous) @ video-rtc.js:312
video-rtc.js:315 Uncaught TypeError: this.ondata is not a function
    at WebSocket.<anonymous> (video-rtc.js:315:22)
```

**Comment by mikedrawback** [comment]
I used to use the option `webrtc: false` to enable AAC sound. how do we do that with the new version? My stream works with `mode: webrtc` but there is no sound. when I set `mode: mse` I get the 'loading' problem mentioned above.

**Comment by kantlivelong** [comment]
Might be useful...

With Firefox(v108) I'm randomly getting the volume/sound when streaming via WebRTC.

According to ffplay
`Stream #0:1: Audio: pcm_mulaw, 8000 Hz, 1 channels, s16, 64 kb/s`

Audio via WebRTC works fine on the HA Android app.

Very exciting to have go2rtc integration! Looking great!

**Comment by AlexxIT** [comment]
@mikedrawback are you sure you using beta.3?

New version will autoselect MSE technology if you have an AAC sound or H265 video.

`webrtc: false` also works, but it deprecated. For manual tech selection use `mode: mse`

**Comment by AlexxIT** [comment]
@kantlivelong you just need to check current streaming technology. It is displayed in the top right corner. `PCMU/8000` can be played only with WebRTC.

**Comment by kantlivelong** [comment]
> @kantlivelong you just need to check current streaming technology. It is displayed in the top right corner. `PCMU/8000` can be played only with WebRTC.

Hmm.. The top right definitely says "RTC" on both Firefox and the HA Android app. Android app has audio. Firefox randomly does.

I'm not sure if the card or go2rtc supports everything listed but according to https://webrtc.github.io/webrtc-org/faq/#what-codecs-are-supported-in-webrtc G.711 is a supported codec which is what `pcm_mulaw` is.

**Comment by kantlivelong** [comment]
@AlexxIT 

Attached is a video showing the issue and how to reproduce. Hope that helps but let me know if you need more info.

https://user-images.githubusercontent.com/1585573/210487966-30d99651-980c-419d-a062-33d755fe5384.mp4

**Comment by mikedrawback** [comment]
When I try `mode: mse` I get this error in console:

```
Uncaught DOMException: Failed to execute 'addSourceBuffer' on 'MediaSource': The type provided ('video/mp4; codecs="avc1.276400,mp4a.40.2"') is unsupported.
    at onmessage.mse (http://192.168.1.168:8123/webrtc/video-rtc.js:391:27)
    at WebSocket.<anonymous> (http://192.168.1.168:8123/webrtc/video-rtc.js:312:41)
onmessage.mse @ video-rtc.js:391
(anonymous) @ video-rtc.js:312
video-rtc.js:315 Uncaught TypeError: this.ondata is not a function
    at WebSocket.<anonymous> (video-rtc.js:315:22)
```

**Comment by vampywiz17** [comment]
> @vampywiz17 I don't know what is "+" feature. Maybe something proprietary from hikvison. They may use an encoding standard not very suitable for live streaming to the browser.

@AlexxIT 

I dont know, that help or not, but if i add my h265+ stream with HA built-in camera card, it working well. (it sometimes buffering a bit, but playing the video)

**Comment by AlexxIT** [comment]
@vampywiz17 try to use ffmpeg source for your stream: `url: ffmpeg:rtsp://...`. There will be no transcoding so CPU will be OK. But FFmpeg may change the frame format. Maybe this will help go2rtc to read them.

**Comment by AlexxIT** [comment]
@mikedrawback I have never saw `avc1.276400` codec. Can you enable rtsp trace log for go2rtc and check response on DESCRIBE request?

**Comment by AlexxIT** [comment]
@kantlivelong check with `mode: webrtc` setting.

**Comment by vampywiz17** [comment]
> @vampywiz17 try to use ffmpeg source for your stream: `url: ffmpeg:rtsp://...`. There will be no transcoding so CPU will be OK. But FFmpeg may change the frame format. Maybe this will help go2rtc to read them.

it need to install addon, right?

**Comment by kantlivelong** [comment]
> @kantlivelong check with `mode: webrtc` setting.

That works. Since the stream initially starts out as MSE (which has no audio likely due to codec incompatibility?) and switches to WebRTC it sounds like the volume slider just isn't being enabled during the transition.

**Comment by AlexxIT** [comment]
@vampywiz17 no. Hass container also has FFmpeg inside.

**Comment by mikedrawback** [comment]
@AlexxIT I enabled debug logging for the integration but I didn't see anything related to the DESCRIBE request

does this help? it is from the go2rtc server api after the stream is created:

```
  {
    "media:0": "video, sendonly, 96 H264/90000",
    "media:1": "audio, sendonly, 97 MPEG4-GENERIC/16000",
    "receive": 577993,
    "remote_addr": "192.168.1.168:554",
    "send": 0,
    "track:0": "97 MPEG4-GENERIC/16000, sinks=1",
    "type": "RTSP client producer",
    "url": "rtsp://192.168.1.182:554/live0",
    "user_agent": "go2rtc/0.1-rc.6"
  },
```

**Comment by vampywiz17** [comment]
> > @vampywiz17 try to use ffmpeg source for your stream: `url: ffmpeg:rtsp://...`. There will be no transcoding so CPU will be OK. But FFmpeg may change the frame format. Maybe this will help go2rtc to read them.
> 
> it need to install addon, right?

I tried it but not help, similar thing happen, but now sometimes i get green picture.

**Comment by mikedrawback** [comment]
I installed go2rtc addon. how do I enable trace log with the hass addon?

**Comment by AlexxIT** [comment]
@mikedrawback Oh, I see. Very bad programmers. What brand and model? They send a broken profile ID. I will fix in next version.

**Comment by AlexxIT** [comment]
@vampywiz17 Right now I don't have time to support a proprietary codec. There are more important tasks about stability. Maybe later. And I will need remote access to the stream.

**Comment by mikedrawback** [comment]
@AlexxIT it is a Eufy camera model T8400

Thank you!

**Comment by vampywiz17** [comment]
> @vampywiz17 Right now I don't have time to support a proprietary codec. There are more important tasks about stability. Maybe later. And I will need remote access to the stream.

understandable!

Thanks the help! if need, i able to help you with stream share.

**Comment by mikedrawback** [comment]
Since the last update to go2rtc this is working better than ever before. thank you @AlexxIT !

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/WebRTC/releases/tag/v3.0.0
