### ISSUE TITLE
Deprecation since 2024.5.0b0

### ISSUE THREAD

**Issue by gieljnssns** [AlexxIT/WebRTC#692]
```
2024-04-25 08:20:40.546 WARNING (ImportExecutor_0) [homeassistant.helpers.typing] HomeAssistantType was used from webrtc, this is a deprecated alias which will be removed in HA Core 2025.5. Use homeassistant.core.HomeAssistant instead, please report it to the author of the 'webrtc' custom integration
2024-04-25 08:20:40.549 WARNING (ImportExecutor_0) [homeassistant.helpers.typing] ServiceCallType was used from webrtc, this is a deprecated alias which will be removed in HA Core 2025.5. Use homeassistant.core.ServiceCall instead, please report it to the author of the 'webrtc' custom integration
```

**Comment by AlexxIT** [comment]
Thanks. I think this is fixed in latest master version

**Comment by TTLucian** [comment]
Hello!
I still get the warnings on HA 2024.5.1, webrtc v3.5.2
```
Logger: homeassistant.helpers.typing
Source: helpers/deprecation.py:206
First occurred: 20:18:00 (2 occurrences)
Last logged: 20:18:00

HomeAssistantType was used from webrtc, this is a deprecated alias which will be removed in HA Core 2025.5. Use homeassistant.core.HomeAssistant instead, please report it to the author of the 'webrtc' custom integration
ServiceCallType was used from webrtc, this is a deprecated alias which will be removed in HA Core 2025.5. Use homeassistant.core.ServiceCall instead, please report it to the author of the 'webrtc' custom integration
```

**Comment by hmmbob** [comment]
Yeah, it is fixed in master already by this commit: https://github.com/AlexxIT/WebRTC/commit/d132c8c351071947eee6b8efb7eb78229d114b9f

So it should be solved when the next version ships. Thanks Alexx!

**Comment by Morpheus2018** [comment]
Same here!
Core 2024.5.3
Supervisor 2024.05.1
Operating System 12.3

**Comment by JeffCrum1** [comment]
Still getting this message in HA 2024.9.2

**Comment by dreimer1986** [comment]
If you want them to vanish so badly, then use the master version. You easily can check when it will be fixed otherwise.
New version?
No? Not fixed.
Yes? Fixed.

**Comment by cloudbr34k84** [comment]
Just adding that im seeing the below 
```
HomeAssistantType was used from webrtc, this is a deprecated alias which will be removed in HA Core 2025.5. Use homeassistant.core.HomeAssistant instead, please report it to the author of the 'webrtc' custom integration
ServiceCallType was used from webrtc, this is a deprecated alias which will be removed in HA Core 2025.5. Use homeassistant.core.ServiceCall instead, please report it to the author of the 'webrtc' custom integration
```

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/WebRTC/releases/tag/v3.6.0
