### ISSUE TITLE
[Feature Request] Ability to restart streaming after stopped

### ISSUE THREAD

**Issue by Perlnx** [AlexxIT/WebRTC#93]
Hello,
![S__285425668](https://user-images.githubusercontent.com/13845123/121861019-a1fa0a80-cd23-11eb-80c0-cc73f252d475.jpg)

I using WebRTC with FullyKiosk browser on tablet.
Network connection to HA server using wired ethernet.

Sometime WebRTC stop streaming and need to refresh Lovelace to restart WebRTC although no connection drop from wired. 
Is it possible to add ability to restart streaming after it stopped or add timeout to reset connection after error occurred ?

**Comment by AlexxIT** [comment]
It should use auto restart already

**Comment by Perlnx** [comment]
First time when I create this topic.
My camera entities configure using UDP transport and I though this can cause interrupt when streaming.
Now I changed to TCP, Streaming seem smoother but it just suddenly stop on 17:00

https://www.youtube.com/watch?v=eOaaFjEG0hs
I record video to show you It not restart automatically. It just spinning indicator forever.

As you saw uptime. It work well for a day without stop.
And there are no network & camera connectivity issue from HA on 17:00

![Capture](https://user-images.githubusercontent.com/13845123/122042557-80bd1b00-ce04-11eb-9078-f2c0e774e21c.JPG)

**Comment by Perlnx** [comment]
Update: Now It's 19:06 and still not reset.

![S__285491204](https://user-images.githubusercontent.com/13845123/122050121-5facf800-ce0d-11eb-9157-63750811d90c.jpg)

**Comment by AlexxIT** [comment]
You can check debug logs for more info
https://github.com/AlexxIT/WebRTC#debug

**Comment by Perlnx** [comment]
Hello,
Just not working today on 19:30.
![S__285548548](https://user-images.githubusercontent.com/13845123/122223778-b255e500-cedd-11eb-8178-88709de2daa6.jpg)

Debug log already turn on but no relate error about WebRTC in that time.

![logger](https://user-images.githubusercontent.com/13845123/122223866-c7327880-cedd-11eb-97d3-18c8e9b34086.PNG)
![Capture](https://user-images.githubusercontent.com/13845123/122223885-cac5ff80-cedd-11eb-9781-f5eba59e3357.PNG)

**Comment by AlexxIT** [comment]
Button "Load full log" under this window

**Comment by Perlnx** [comment]
Sorry I didn't notice that.
Here full logs.

![2021-06-16_20-45-00](https://user-images.githubusercontent.com/13845123/122231121-6ce8e600-cee4-11eb-8f15-6f32ddfd13e8.png)

**Comment by AlexxIT** [comment]
This is error from main Home Assistant code. I don't know if it because of WebRTC. But seems like it breaks WebRTC component.

**Comment by Perlnx** [comment]
The lasted error from supervisor It came from when I update supervisor today.
Not sure about EOF message. Is that relate to keyframe ?
Since my substream using default 50 with framerate 20.

![Capture](https://user-images.githubusercontent.com/13845123/122243554-69f2f300-ceee-11eb-9e77-33dc15e7fca9.PNG)


I will try to restart HA to clear log and collect info again tomorrow.

**Comment by AlexxIT** [comment]
websocket EOF it is normal situation. Lovelace breakes connection to server when WebRTC starts streaming.

**Comment by Perlnx** [comment]
I see, Can you tell me which line that Lovelace breaks connection. So I will ask the other next.

**Comment by Perlnx** [comment]
Today it stopped on 22:09.
![S__285679618](https://user-images.githubusercontent.com/13845123/122427260-2a460d00-cfbb-11eb-873c-28e549945fc2.jpg)

This is HA log (I didn't do anything with HA this day)
![2021-06-17_22-22-31](https://user-images.githubusercontent.com/13845123/122427620-7729e380-cfbb-11eb-9d1e-8c07dea14ea8.png)

Seem like It always stopped after 1 day of streaming.

**Comment by majdzik84** [comment]
I am experiencing this problem too. Every once in a while the image gets lost on my dashboard. Refreshing the screen reloads the camera correctly.
![image](https://user-images.githubusercontent.com/31352476/125161566-518b9680-e183-11eb-90a8-a25a391b8b97.png)

**Comment by Perlnx** [comment]
Sorry to hear this. I'm give up and roll back to picture entity instead.
Since the debug log can't find anything relate to this and I cannot fix this by myself.

Actually I just need ability to auto refresh playback after message Error: No Video appear.

**Comment by waleed-alharthi** [comment]
I have the same issue, maybe for a short term workaround we can use a browser plugin to automatically refresh the screen every N minutes.

**Comment by AlexxIT** [comment]
Should be fixed in v3

**Comment by mbrevda** [comment]
Pretty sure I'm still experiencing this: lovelace in Fully loads fine, then after some time the video stops and requires a refresh of the entire page to start again. Is there something I can do to debug/fix?
